//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TRIZBD
{
    using System;
    using System.Collections.Generic;
    
    public partial class Feedback
    {
        public int Id_feedback { get; set; }
        public int Id_event { get; set; }
        public int Id_participant { get; set; }
        public Nullable<int> rating { get; set; }
        public string comment { get; set; }
    
        public virtual Event Event { get; set; }
        public virtual Participant Participant { get; set; }
    }
}
