//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TRIZBD
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_ActiveParticipants
    {
        public int Id_participant { get; set; }
        public string participant_name { get; set; }
        public string phone { get; set; }
        public Nullable<int> events_attended { get; set; }
    }
}
