//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TRIZBD
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_LowRatedEvents
    {
        public int Id_event { get; set; }
        public string event_name { get; set; }
        public System.DateTime date { get; set; }
        public Nullable<int> average_rating { get; set; }
        public Nullable<int> feedback_count { get; set; }
    }
}
