//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TRIZBD
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_OrganizersWithEvents
    {
        public int Id_organizer { get; set; }
        public string organizer_name { get; set; }
        public string position { get; set; }
        public Nullable<int> events_count { get; set; }
        public string event_names { get; set; }
    }
}
